# Generated by Django 4.2 on 2026-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_ats_score_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_found',
            field=models.TextField(blank=True, null=True),
        ),
    ]
