# Generated by Django 4.2 on 2026-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
