# Generated by Django 4.2 on 2026-06-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_register_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
